spring.application.name=services2-currencyexchange-app

spring.datasource.url=jdbc:mysql://localhost:3306/r_services1
spring.datasource.username=root
spring.datasource.password=semvak4dny4830412
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.config.import=optional:configserver:http://localhost:8888

server.port=8001

# set naming server untuk eureka servernya
# berisi [] karena config nya tipe map, makanya perlu gitu
# tapi keknya udh default di configin ama springnya
# sebenarnya gabisa pake [] untuk set key map nya, yg bener itu langsung dikasi . yaitu service-url.defaultZone untuk ngasi variable pada key tsb
eureka.client.service-url["defaultZone"]=http://localhost:8761/eureka

# mengset persentase tiap request yg diterima oleh service yg akan
# dikirim ke server distributed tracing, untuk di monitor
management.tracing.sampling.probability=1.0

# mengatur format lognya agar nanti traceId ama spanId nya keliatan, gunanya untuk mengetahui request mana yg dikirim ke server DT
# cek aja isi code config ini
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
