# memberi nama application untuk projek ini, agar mempermudah banyak hal nantinya
spring.application.name=r_configserver1-spring

# sebagai standar port untuk central config spring cloud
server.port=8888
