# memberi nama application untuk projek ini, agar mempermudah banyak hal nantinya
spring.application.name=r_configserver1-spring

# sebagai standar port untuk central config spring cloud
server.port=8888

# untuk mengkonekan konfigurasi parent (git repo) ke projek server config ini
# yg nanti akan bisa diakses melalui local:8888/limit-services-app/default dimana path ke 2 perlu sesuai dengan nama file properties yg ada pada repo git config
spring.cloud.config.server.git.uri=file:///D:/_code/_project_second/java/_microservices1/git-local-config