
spring.application.name=naming-server1

spring.config.import=optional:configserver:http://localhost:8888

# port untuk standar naming server
server.port=8761

# digunakan agar server/instance eureka yg dijalankan ini tidak mengregistrasi itself / dirinya sendiri ke list instance pada eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

