
spring.application.name=naming-server1

spring.config.import=optional:configserver:http://localhost:8888

# port untuk standar naming server
server.port=8761

# katanya agar spesifik server tidak register dengan itself?
eureka.client.register-with-eureka=false

eureka.client.fetch-registry=false

