# jadi nama application ini harus sesuai ama file yg ada di git-repo-config
# agar ketika request property yg diambil sesuai dengan file yg diperlukan
spring.application.name=data1

# konfigurasi yg required ketike memakai depend spring cloud config client
spring.config.import=optional:configserver:http://localhost:8888

# ketika sudah nge import config dari server
# properties priority yg ada disini lebih rendah ketika propertynya ada yg duplicate dgn server config
#limit-service.minimum=5
#limit-service.maximum=950
