
spring.application.name=api-gateway1

# default port untuk api gateway
server.port=8765

# ini optional sebenarnya, karena defaultZone sudah otomatis di define oleh eureka client
eureka.client.service-url["defaultZone"]=http://localhost:8761/eureka