
spring.application.name=api-gateway1

# default port untuk api gateway
server.port=8765

# ini optional sebenarnya, karena defaultZone sudah otomatis di define oleh eureka client


# set tipe map bisa dilakukan dengan menambahkan prop.key=value, bukan prop[key] = value
# begitupun dengan map<String, Obj> prop.key.prop-dalam-obj=value
eureka.client.service-url["defaultZone"]=http://localhost:8761/eureka


# untuk meng enable/atifkan discovery client gateway
#   yang fungsinya untuk membuatkan locator path untuk tiap service
#   jadi kalo ini enable, jadinya ngga perlu ngebikin Config Gateway nya menggunakan RouteLocator
#   kalo mau pake RouteLocator, bisa di disable aja ini, atau set = false
# dimana nanti config ini akan membuat api-gateway nya bisa dipanggil dengan path dari application.name service lain
#   eg http://localhost:8765/SERVICES2-CURRENCYEXCHANGE-APP/currency-exchange/from/idr/to/usd
#   eg http://localhost:8765/SERVICES3-CURRENCY-CONVERSION1/currency-exchange/from/idr/to/usd/quantity/235
#
# liat aja inside comment confignya
spring.cloud.gateway.discovery.locator.enabled=false
# set default false karena udh pakai GetewayConfig

# untuk enable application name agar pathnya bisa di panggil dengan lowercase
# from this http://localhost:8765/SERVICES2-CURRENCYEXCHANGE-APP/currency-exchange/from/idr/to/usd
# to this http://localhost:8765/services2-currencyexchange-app/currency-exchange/from/idr/to/usd
spring.cloud.gateway.discovery.locator.lower-case-service-id=false
# set default false karena udh pakai GetewayConfig

eureka.instance.prefer-ip-address=true

# mengset persentase tiap request yg diterima oleh service yg akan
# dikirim ke server distributed tracing, untuk di monitor
management.tracing.sampling.probability=1.0

# mengatur format lognya agar nanti traceId ama spanId nya keliatan, gunanya untuk mengetahui request mana yg dikirim ke server DT
# cek aja isi code config ini
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]