
spring.application.name=services3-currency-conversion1

spring.config.import=optional:configserver:http://localhost:8888

# note tambahan pada r-currency-exchange
# ini optional
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# note untuk set value tipe map bisa dilakukan dengan menambahkan prop.key=value, bukan prop[key] = value
# begitupun dengan map<String, Obj> prop.key.prop-dalam-obj=value

# nanti bisa digunakana @Retry(name = "hooh-api1") agar retry nya dilakukan sebanyak 5 kali
resilience4j.retry.instances.hooh-api1.max-attempts=5