
spring.application.name=services3-currency-conversion1

spring.config.import=optional:configserver:http://localhost:8888

# note tambahan pada r-currency-exchange
# ini optional
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# note untuk set value tipe map bisa dilakukan dengan menambahkan prop.key=value, bukan prop[key] = value
# begitupun dengan map<String, Obj> prop.key.prop-dalam-obj=value

# nanti bisa digunakana @Retry(name = "hooh-api1") agar retry nya dilakukan sebanyak 5 kali
resilience4j.retry.instances.hooh-api1.max-attempts=5

# mengset persentase tiap request yg diterima oleh service yg akan
# dikirim ke server distributed tracing, untuk di monitor
management.tracing.sampling.probability=1.0

# mengatur format lognya agar nanti traceId ama spanId nya keliatan, gunanya untuk mengetahui request mana yg dikirim ke server DT
# cek aja isi code config ini
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]